Fixes for macOS (#68)
* Fix compilation on macOS

src/e_main.cc:1484:20: error: expected ')'
src/e_main.cc:1866:13: error: use of undeclared identifier 'E_TITLE'
src/e_main.cc:2065:29: error: expected ')'

* Fix linking on macOS

Link with SDL2 library and IOKit framework
Use Vorbis .dylib

* Update Travis configuration to use Xcode 10.1

This reduces time of macOS build because Homebrew update completes faster with newer VM image