Added explicit linking to libdl for POSIX targets
This fixes linker the following linker errors when non-default compiler is used
/usr/bin/ld: src/system/GL/gl_load.c.o: undefined reference to symbol 'dlsym@@GLIBC_2.2.5'
/lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line